### ISSUE TITLE
Clarify macOS (OS X) options in download.html

### ISSUE THREAD

**Issue by JDLH** [ApacheFriends/web#13]
Apply the changes of https://github.com/ApacheFriends/web-static/pull/4 here, to the upstream Middleman source files. Then propagate to the web-static files. That Pull Request says,

Clarify the difference between native and VM packages for macOS in download page.

Add a paragraph explaining the difference between native installation and VMs. Clearly announce that VM option does not support M1 (arm64) CPUs. In the macOS title listing the 6 versions, add "native" and "VM" clarification. In each download entry, add "native" and "VM" clarification phrases.

In the System Requirements text, clarify that native installers require x64 or arm64, but that VM requires x64 and does not support arm64.

**Comment by beltran-rubo** [comment]
Those were applied as part of https://github.com/ApacheFriends/web/pull/16, thanks!
