### ISSUE TITLE
Add instructions on how to contribute to documentation to the website

### ISSUE THREAD

**Issue by JDLH** [ApacheFriends/web#15]
In the ApacheFriends website, in the instructions on how to contribute, make sure there are clear instructions for how to contribute to the documentation. That should include links to the https://github.com/ApacheFriends/web and https://github.com/ApacheFriends/web-static repositories, and instructions that changes should be made to the Middleman sources upstream in the /web repo, and instructions for how to get changes accepted and pushed out to the website.

Background: I just noticed two things I wanted to fix about the website, I followed what instructions I could find, and I ended up at the wrong repo (/web-static instead of /web). The purpose of this task is to save the next person from making the mistake I made.

**Comment by beltran-rubo** [comment]
In the `web-static` repo is already a note to clarify the contributions:

> This is the repository for the static files for the Apache Friends website. The website is based on [Middleman](https://middlemanapp.com/) and the code to generate it is available at [web repository](https://github.com/ApacheFriends/web).
> 
> All the PRs in this repo should be contributed first into the [web repository](https://github.com/ApacheFriends/web).
